# create -  docker compose -f docker/docker-compose.postgres.yml up -d 
version: '3.8'

name: n8n

services:
  db:
    image: postgres:16
    container_name: pg-n8n
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: n8n
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: